function header = get_emgheader(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SPBASELINE = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a string array.
%
%  SPBASELINE = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  SPbaseline = importfile("/Users/hjhuang/Dropbox (Personal)/_DATA/FE/Rawdata/EMG/FE1/2024-03-08-12-35_SPbaseline.csv", [4, 4]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 05-Apr-2024 12:29:23

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, 4];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 18, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "Activity", "Marker", "LTBICEPSFEMuV", "LTLATGASTROuV", "LTMEDGASTROuV", "LTSOLEUSuV", "LTRECTUSFEMuV", "LTVLOuV", "LTTIBANTuV", "RTBICEPSFEMuV", "RTLATGASTROuV", "RTMEDGASTROuV", "RTSOLEUSuV", "RTRECTUSFEMuV", "RTVLOuV", "RTTIBANTuV", "UltiumEMGSyncOn"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["time", "Activity", "Marker", "LTBICEPSFEMuV", "LTLATGASTROuV", "LTMEDGASTROuV", "LTSOLEUSuV", "LTRECTUSFEMuV", "LTVLOuV", "LTTIBANTuV", "RTBICEPSFEMuV", "RTLATGASTROuV", "RTMEDGASTROuV", "RTSOLEUSuV", "RTRECTUSFEMuV", "RTVLOuV", "RTTIBANTuV", "UltiumEMGSyncOn"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["time", "Activity", "Marker", "LTBICEPSFEMuV", "LTLATGASTROuV", "LTMEDGASTROuV", "LTSOLEUSuV", "LTRECTUSFEMuV", "LTVLOuV", "LTTIBANTuV", "RTBICEPSFEMuV", "RTLATGASTROuV", "RTMEDGASTROuV", "RTSOLEUSuV", "RTRECTUSFEMuV", "RTVLOuV", "RTTIBANTuV", "UltiumEMGSyncOn"], "EmptyFieldRule", "auto");

% Import the data
header = readmatrix(filename, opts);

end