function emgdata = import_emg(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SPBASELINE = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  SPBASELINE = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  SPbaseline = importfile("/Users/hjhuang/Dropbox (Personal)/_DATA/FE/Rawdata/EMG/FE1/2024-03-08-12-35_SPbaseline.csv", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Apr-2024 12:04:15

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% get emg header
header = get_emgheader(filename);

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 18, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
% opts.VariableNames = ["time", "Activity", "Marker", "LTBICEPSFEMuV", "LTLATGASTROuV", "LTMEDGASTROuV", "LTSOLEUSuV", "LTRECTUSFEMuV", "LTVLOuV", "LTTIBANTuV", "RTBICEPSFEMuV", "RTLATGASTROuV", "RTMEDGASTROuV", "RTSOLEUSuV", "RTRECTUSFEMuV", "RTVLOuV", "RTTIBANTuV", "UltiumEMGSyncOn"];
opts.VariableNames = header;
opts.VariableTypes = ["double", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Activity", "Marker"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Activity", "Marker"], "EmptyFieldRule", "auto");

% Import the data
emgdata = readtable(filename, opts);

end