function emgdata = import_emg(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FE1BPM15EMG = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  FE1BPM15EMG = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  FE1bpm15emg = importfile("/Volumes/Extreme SSD/Testing_FE/EMG/FE1/FE1_bpm15_emg.txt", [6, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Apr-2024 14:26:55

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [6, Inf];
end

%% get emg header
%header = get_emgheader(filename);

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Times", "BICEPSFEMLTuV", "LATGASTROLTuV", "MEDGASTROLTuV", "SOLEUSLTuV", "RECTUSFEMLTuV", "VLOLTuV", "TIBANTLTuV", "BICEPSFEMRTuV", "LATGASTRORTuV", "MEDGASTRORTuV", "SOLEUSRTuV", "RECTUSFEMRTuV", "VLORTuV", "TIBANTRTuV", "Var16"];
opts.SelectedVariableNames = ["Times", "BICEPSFEMLTuV", "LATGASTROLTuV", "MEDGASTROLTuV", "SOLEUSLTuV", "RECTUSFEMLTuV", "VLOLTuV", "TIBANTLTuV", "BICEPSFEMRTuV", "LATGASTRORTuV", "MEDGASTRORTuV", "SOLEUSRTuV", "RECTUSFEMRTuV", "VLORTuV", "TIBANTRTuV"];
%opts.VariableNames = header;
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var16", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var16", "EmptyFieldRule", "auto");

% Import the data
emgdata = readtable(filename, opts);

end